spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: latest     # 从最新消息开始消费（开发用）
    listener:
      missing-topics-fatal: false   # topic 不存在时不报错
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer